tasks:
  - name: Install, Build & Run
    before: |
      # Install JDK
      echo "Installing JDK ..."
      sdk install java 17.0.4.1-tem < /dev/null

      # Gradle
      gradle wrapper
      ./gradlew bootJar
    command: |
      # Start application on port 8080
      #echo "Starting application..."
      #./gradlew bootRun
      echo "Start the application by running ./gradlew bootRun - You can use [control + C] to stop running your application."

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
